server:
  port: 8080
spring:
  application:
    name: sercurity_auth
  security:
    user:
      name: admin
      password: admin123456
  datasource:
    username: root
#    家里mysql
    password: 123456
    url:  jdbc:mysql://127.0.0.1:3306/local_db?useUnicode=true&nullCatalogMeansCurrent=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8

    #    公司mysql
#    password: 123456
#    url:  jdbc:mysql://127.0.0.1:3306/start_local_db?useUnicode=true&nullCatalogMeansCurrent=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  activiti:
#    检查表结构是否存在   默认FALSE
    database-schema-update: true
    check-process-definitions: true
    #process-definition-location-prefix 是指定activiti流程描述文件的前缀（即路径）
    process-definition-location-prefix: classpath:/
#    suffix 是一个String数组，表示描述文件的默认后缀名，默认以上两种。
    #    process-definition-location-suffixes:
    #      - **.bpmn
    #      - **.bpmn20.xml
#    需要加上这个注解，不然会少生成8张表
    historyLevel: audit
    db-history-used: true
  thymeleaf:
    prefix: classpath:/templates/

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml

logging:
  level:
    root: info
    com:
      auth:
        Sercurity: debug
    org:
      activiti:
        engine:
          impl:
            persistence:
              entity: debug
  config: classpath:log/logback-spring.xml
  file: classpath:log/app-log.log